### ISSUE TITLE
New release for LLVM 16 support?

### ISSUE THREAD

**Issue by thesamesam** [marxin/cvise#111]
Hi,

Thanks for cvise! For LLVM 16 support, 2f4e1755aa32b131b49606cd55b5bfcc7714a8a8 is needed which was committed post-tag, any chance of a new release containing that? 

I've pulled it in for Gentoo but there's some other nice looking bits in master so figured I'd ask :)

thanks!

**Comment by marxin** [comment]
Sure, good point, I've just done that:
https://github.com/marxin/cvise/releases/tag/v2.8.0

**Comment by marxin** [comment]
Thank you! Glad to have happy users.
