### ISSUE TITLE
ability to use /bin/sh for --commands

### ISSUE THREAD

**Issue by nekopsykose** [marxin/cvise#119]
cvise supports `--commands` to quickly specify a simple test instead of needing to write a script:  

```
--commands COMMANDS, -c COMMANDS
                      Use bash commands instead of an interestingness test case
```

[the implementation](https://github.com/marxin/cvise/blob/4b129f72aaf0f6c8b16669ad619410a914b0bdff/cvise.py#L293C1-L293C1) matches the description, and writes a file with `bash` in the shebang.  

personally i don't keep bash installed (not hard to acquire or anything, but i keep all my scripts to regular `sh` as i'm just used to that). it would be nice if it was possible to either default it to sh instead (though admittedly this would be a regression for some number of people, e.g. especially for the convenient `|&` shorthand i'm sure people use in bash), or allow `--sh` or similar (`--shell sh` ?) to write a `#!/bin/sh` shebang instead of requiring bash for the feature.

**Comment by marxin** [comment]
Thanks for the issue and I've just implemented the suggested `--shell` option. Enjoy.

**Comment by nekopsykose** [comment]
thanks!
