### ISSUE TITLE
Idiomatic way to avoid reductions on some parts of the code?

### ISSUE THREAD

**Issue by rmonat** [marxin/cvise#125]
I'd like to run cvise on a program `small.c` where some specific lines should not be reduced. I tried adding them at the beginning of the oracle script and removing them at the end, but that doesn't work well. Is there an idiomatic way to do that?

EDIT: My current approach is to copy the file and let the rest of my oracle run on the copy, that seems to work decently.

**Comment by marxin** [comment]
I think the best way is to add a collection of **grep** commands to the interest. test script, where you search for the specific lines. Does it work for you?

**Comment by rmonat** [comment]
Thank you, I'll look into it. I'm afraid this will conflict with the potential reductions, but at least the feedback will be quick.
