### ISSUE TITLE
cvise fails to build with LLVM 18.1.0

### ISSUE THREAD

**Issue by doko42** [marxin/cvise#127]
after pulling the one LLVM 18 fix from master, cvise fails to build with errors induced by -Werror (deprecated warnings),

replacing .startswith with .starts_with in the .cpp files avoids that (but don't do that in the .py files).

**Comment by marxin** [comment]
Sure, I disable the Werror for the warning right now: https://github.com/marxin/cvise/blob/f0e1387872b6959995e81e59d97d89514eebfb92/CMakeLists.txt#L195-L198

Why is it not working for you? What version of C-Vise do you use?

**Comment by doko42** [comment]
2.9.0, together with your LLVM-18 fix from the trunk

**Comment by marxin** [comment]
Then please provide a complete build log (with `make VERBOSE=1` output).

**Comment by marxin** [comment]
Does it work now?

**Comment by doko42** [comment]
yes, https://buildd.debian.org/status/package.php?p=cvise
