### ISSUE TITLE
Cvise stopped abnormally midway

### ISSUE THREAD

**Issue by martinwz** [marxin/cvise#147]
Hi, I was using Cvise to reduce my c code. However, Cvise stopped after running for 20 minutes, as shown in the figure. My environment is Ubuntu 18.04, Python 3.8.6, and clang 10. What went wrong?
![image](https://github.com/user-attachments/assets/0d83aac7-228a-4c4d-aae5-3532ee4f7aad)

**Comment by marxin** [comment]
Hey! Thanks for using C-Vise tool. Please share a reproducer I can use and the full log output of the reduction. And please include which C-Vise version do you use?

**Comment by martinwz** [comment]
> Hey! Thanks for using C-Vise tool. Please share a reproducer I can use and the full log output of the reduction. And please include which C-Vise version do you use?


I build cvise 2.10 from the source code. I'm sorry, I can't provide reproducible files. I reduce C code and I used C code to test a large commerical compiler (mainly 100+GB). It is difficult to share and download the compiler. So, is there any other way to help locate the problem?

**Comment by marxin** [comment]
Ok, that's fine. So let's try a remote debugging session. I will need to know:

- Full log output of the reduction.
- Can you reproduce the problem every time? If so, is it somehow tight to a particular reduction pass?
- What version of https://pypi.org/project/Pebble/ do you use?
- Can you test it on a more modern Ubuntu distro (`24.04`)?

**Comment by martinwz** [comment]
Sorry, I did not save the origianl log outpuit but I can provide a similar one. The full log is shown in the file. The version Pebble is 5.0.7 and I can reproduce the problem every time. My workspaces are build on  Ubuntu 18.04, so it is difficult to test it on a more modern Ubuntu now. I will it later.
[full_log.txt](https://github.com/user-attachments/files/16450856/full_log.txt)

**Comment by marxin** [comment]
All right, it seems I missed catching a `TimeoutError` from Pebble. Can you please test the PR #148?

Anyway, I would recommend running a reduction command wrapped in a meaningful timeout (I bet your compiler should not spend 300s compiling a rather small input, right?).

`cvise -c 'timeout 10 g++ tramp3d-v4.ii ...` can help you.
