### ISSUE TITLE
Unable to run cvise from build location without installing

### ISSUE THREAD

**Issue by andrewvaughanj** [marxin/cvise#3]
I just built **but did not install** `cvise`, so tired running it from the build location, but this failed with `cvise` being unable to find the tools for doing the passes.

I solved this by doing this:

```
export PATH=~/cvise/build/clex/:~/cvise/build/clang_delta:~/cvise/build:~/cvise/build/cvise:~/creduce/unifdef:~/creduce/delta/:$PATH
```

which *also* requires `unifdef` and `topflatformat`, which do not appear to be part of a normal `cvise` build (but they are part of a `creduce` build!).

I guess it needs to be documented that, if you want to run a non-installed build of `cvise`, you need to set `$PATH`, and that you need to install `unifdef` and `topflatformat` "from somewhere else".

`unifdef` (e.g.,) is listed in the Fedora Dockerimage, but I couldn't find this documented anywhere else.

**Comment by marxin** [comment]
> I just built **but did not install** `cvise`, so tired running it from the build location, but this failed with `cvise` being unable to find the tools for doing the passes.
> 
> I solved this by doing this:
> 
> ```
> export PATH=~/cvise/build/clex/:~/cvise/build/clang_delta:~/cvise/build:~/cvise/build/cvise:~/creduce/unifdef:~/creduce/delta/:$PATH
> ```

You are right, I'm going to support local search of `clang_delta` and `clex`.

> 
> which _also_ requires `unifdef` and `topflatformat`, which do not appear to be part of a normal `cvise` build (but they are part of a `creduce` build!).

Yes, I decided to exclude the third party programs from `cvise` build.

> 
> I guess it needs to be documented that, if you want to run a non-installed build of `cvise`, you need to set `$PATH`, and that you need to install `unifdef` and `topflatformat` "from somewhere else".
> 
> `unifdef` (e.g.,) is listed in the Fedora Dockerimage, but I couldn't find this documented anywhere else.

I documented them to `INSTALL.md` and makes detection of them.

**Comment by andrewvaughanj** [comment]
> You are right, I'm going to support local search of clang_delta and clex.
>

Ideal!

> Yes, I decided to exclude the third party programs from cvise build.
>

I have zero issues with that ... this was an "observation" rather than a criticism (and would explain why I added `creduce` to `$PATH` to work with `cvise`).

> I documented them to INSTALL.md and makes detection of them.
>

Awesome!

**Comment by marxin** [comment]
Fixed now.
