### ISSUE TITLE
cvise --help fails

### ISSUE THREAD

**Issue by doko42** [marxin/cvise#32]
this is a regression in 1.5, compared to 1.4:

cvise --help
Traceback (most recent call last):
  File "debian/cvise/usr/bin/cvise", line 166, in <module>
    passes_group.add_argument("--pass-group", type=str, choices=get_available_pass_groups(), help="Set of passes used during the reduction")
  File "debian/cvise/usr/bin/cvise", line 113, in get_available_pass_groups
    CVise.parse_pass_group_dict(pass_group_dict, set(), None, None, None, None, None)
TypeError: parse_pass_group_dict() takes 7 positional arguments but 8 were given

**Comment by marxin** [comment]
Hm, I can't reproduce the problem with both `v1.5.0` and `master`. It seems you combine a new and old `.py` files from different versions.
