### ISSUE TITLE
no declaration matches ‘bool clang::RecursiveASTVisitor<Derived>::TraverseCXXAddrspaceCastExpr(clang::CXXAddrspaceCastExpr*, clang::RecursiveASTVisitor<Derived>::DataRecursionQueue*)’

### ISSUE THREAD

**Issue by nickdesaulniers** [marxin/cvise#37]
trying to build cvise from source again, I see:
```
In file included from ../clang_delta/ClassTemplateToClass.cpp:17:
/android0/llvm-project/clang/include/clang/AST/RecursiveASTVisitor.h:2154:8: error: no declaration matches ‘bool clang::RecursiveASTVisitor<Derived>::TraverseCXXAddrspaceCastExpr(clang::CXXAddrspaceCastExpr*, clang::RecursiveASTVisitor<Derived>::DataRecursionQueue*)’
```
maybe out of date against ToT LLVM?

**Comment by marxin** [comment]
That's quite strange as I can't find the mentioned function `TraverseCXXAddrspaceCastExpr` in both LLVM project and `cvise` source files. Are you sure you have vanilla LLVM?

**Comment by nickdesaulniers** [comment]
strange, I just rebuilt and it worked. Only warning was:
```
[2/74] Building CXX object clang_delta/CMakeFiles/clang_delta.dir/TransformationManager.cpp.o
In file included from ../clang_delta/TransformationManager.cpp:25:
In file included from /android0/llvm-project/clang/include/clang/Frontend/CompilerInstance.h:15:
In file included from /android0/llvm-project/clang/include/clang/Frontend/CompilerInvocation.h:22:
/android0/llvm-project/clang/include/clang/StaticAnalyzer/Core/AnalyzerOptions.h:437:9: warning: 'PACKAGE' macro redefined [-Wmacro-redefined]
#define PACKAGE(FULLNAME) llvm::StringLiteral(FULLNAME),
        ^
./config.h:35:9: note: previous definition is here
#define PACKAGE "cvise"
        ^
1 warning generated.
```
Maybe my llvm-project tree was in a weird state; I was bisecting LLVM recently. Sorry for the noise.

**Comment by nickdesaulniers** [comment]
I was able to run cvise to help reduce a test case! Thanks @marxin for all of the work that went into building cvise!
https://github.com/ClangBuiltLinux/linux/issues/1161

**Comment by marxin** [comment]
> I was able to run cvise to help reduce a test case! Thanks @marxin for all of the work that went into building cvise!
> [ClangBuiltLinux/linux#1161](https://github.com/ClangBuiltLinux/linux/issues/1161)

Glad to hear that!
