### ISSUE TITLE
cannot find external program {clang_delta|clex|clang-format}

### ISSUE THREAD

**Issue by nickdesaulniers** [marxin/cvise#38]
Hello!

I ran `cvise` today and get a bunch of warnings:
```
00:00:00 ERROR Prereqs not found for pass ClangPass::vector-to-array
00:00:00 ERROR cannot find external program clang_delta
00:00:00 ERROR Prereqs not found for pass ClangPass::remove-try-catch
00:00:00 ERROR cannot find external program clang-format
00:00:00 ERROR Prereqs not found for pass IndentPass::regular
00:00:00 ERROR cannot find external program clex
```
`cvise` still ran to completion, but it looks like some passes were skipped because these are missing.

`clang-format` is in my $PATH; `clang_delta` and `clex` are not.  (I haven't heard of those latter two)  Not sure if this is an issue with relative paths based on how I ran `cvise`:

```sh
$ cd <dir that's not cvise sources>
$ /<abs path to>/cvise/cvise.py --n 71 ./repro.sh slub.i   
```

or if I've probably not enabled `clang-tools-extra` for my build of llvm?

**Comment by nickdesaulniers** [comment]
> Not sure if this is an issue with relative paths based on how I ran cvise

Yep,
cvise/build/cvise.py works
cvise/cvise.py does not.

**Comment by nickdesaulniers** [comment]
another trophy for cvise: https://bugs.llvm.org/show_bug.cgi?id=47837#c6

**Comment by nickdesaulniers** [comment]
Just abusing the issue to mention to @marxin that I was able to use cvise to reduce a test case written in assembler by using the `--non-c` flag (or whatever it is called) the other day! Very helpful!

**Comment by marxin** [comment]
Glad to hear that! I guess LinesPass made the biggest progress, right?

**Comment by nickdesaulniers** [comment]
yes; if there was a way to run just LinesPass without other passes that would be helpful, too.

**Comment by marxin** [comment]
You can use `cvise-delta` binary that runs only the LinesPass.
