### ISSUE TITLE
Can `cvise`'s intermediate files be trusted?

### ISSUE THREAD

**Issue by andrewvaughanj** [marxin/cvise#4]
I'm giving `cvise` a try on top of some examples I've been using with `creduce` -- I took the inputs and interestingness test directly from something that worked for `creduce`.

I let `cvise` run for only a few minutes, with this on `stdout`:

```
INFO ===< 69135 >===
INFO running 97 interestingness tests in parallel
INFO INITIAL PASSES
INFO ===< IncludesPass >===
INFO (0.1%, 22991 bytes)
INFO ===< UnIfDefPass >===
INFO ===< CommentsPass >===
INFO ===< IfPass >===
INFO ===< LineMarkersPass >===
INFO ===< BlankPass >===
INFO ===< ClangBinarySearchPass::replace-function-def-with-decl >===
INFO ===< ClangBinarySearchPass::remove-unused-function >===
INFO ===< LinesPass::0 >===
INFO ===< LinesPass::1 >===
```

I copied the input file (which `cvise` had modified in place) to another directory and ran the "interesting test" manually ... and it failed!

Looking at the intermediate hand by eye, I agree that the file should no longer pass the interestingness test.

Is the updated file on disk supposed to always pass the interestingness test (like it does with `creduce`)?

**Comment by marxin** [comment]
> Is the updated file on disk supposed to always pass the interestingness test (like it does with `creduce`)?

Yes.
Can you please provide a test-case and attach it here?

**Comment by andrewvaughanj** [comment]
Haha, well, I might need a test-suite reducer for that!

More seriously, I will see what I can do; sharing the input is probably fine -- however, the "interestingness test" relies on running MSVC under Wine (it does work fine under `creduce` though).

I'm currently reducing a > 5 MiB TU -- to do that, I'm actually incrementally starting from the _unpreprocessed_ source and then manually expanding one level of headers at a time. I noticed that `cvise` had (very quickly) removed a required `#include`.

Could this explain things?

**Comment by marxin** [comment]
> More seriously, I will see what I can do; sharing the input is probably fine -- however, the "interestingness test" relies on running MSVC under Wine (it does work fine under `creduce` though).

It's a complicated test-case.

> I'm currently reducing a > 5 MiB TU -- to do that, I'm actually incrementally starting from the _unpreprocessed_ source and then manually expanding one level of headers at a time. I noticed that `cvise` had (very quickly) removed a required `#include`.

It must be work of either `IncludeIncludesPass` or `IncludesPass`, which is positive!

> 
> Could this explain things?

Probably not. Note that I've already run `cvise` quite many times and it really updates the original test that is reduced and so that the interestingness test should still succeed.
Do you reduce just a single file?

**Comment by andrewvaughanj** [comment]
> Do you reduce just a single file?

Yep! Here's the script:

```
#!/bin/bash

export INPUT=cpp17_std_includes.cpp
OBJ=$(basename ${INPUT} .cpp).obj
TU=$(basename ${INPUT} .cpp).tu.cpp

trap 'rm -f ${OBJ} ${TU}' TERM

wine64 cl.exe /std:c++17 /wd4996 /WX /W4 /EHsc /c /Tp ${INPUT} > /dev/null 2>&1

test -f ${OBJ}
exists=$?

rm -f ${OBJ}

if [[ ${exists} -eq 1 ]]; then
    exit 1;
fi

wine64 cl.exe /std:c++17 /wd4996 /WX /W4 /EHsc /D_HAS_CONDITIONAL_EXPLICIT=0 /E /Tp ${INPUT} > ${TU} 2>/dev/null

~/master/edgfe --edg -w --c++17 --microsoft --microsoft_version 1920 ${TU} > /dev/null 2>&1

if [[ $? -ne 0 ]]; then
    exit 1;
fi

~/branch/edgfe --edg -w --c++17 --microsoft --microsoft_version 1920 ${TU} > /dev/null 2>&1

if [[ $? -eq 0 ]]; then
    exit 1;
fi

rm -f ${OBJ} ${TU}

exit 0

# EOF
```

I've run this script for _days_ at a time and `creduce` has always had "working" intermediate files.

The top of my input looks like this:

```
#define _XTR1COMMON_
#include <yvals_core.h>
#pragma pack(push, _CRT_PACKING)
#pragma warning(push, _STL_WARNING_LEVEL)
#pragma push_macro("new")
#undef new
```

and `cvise` removed the include to `yvals_core.h` but was still processing.

**Comment by andrewvaughanj** [comment]
Command line: `~/cvise/build/cvise.py -n 97 --clang-delta-std c++17 test.sh cpp17_std_includes.cpp`

**Comment by marxin** [comment]
That would be the problem, you don't accept an argument of the script.
I use:
```sh
#!/bin/sh

TC1=${1:-ice.i}

/home/marxin/Programming/creduce-benchmarks/pr94526-m68k-ice/cc1 -fpreprocessed -quiet -O2 -g $TC1 -o /dev/stdout 2>&1 | grep 'new_elt_loc_list'
```

what happens is that the `cpp17_std_includes.cpp` is reduced in a temporary folder, but check script runs the interestingness test still for the original one.

I printed command line of int. script and it's something like:
```
'/home/marxin/Programming/creduce-benchmarks/pr94526-m68k-ice/reduce-ice.sh', '/tmp/cvise-advs98nn/cvise-c47dq3ob/ice.i'
```

**Comment by andrewvaughanj** [comment]
That's really interesting ... so that means it is _different_ to `creduce`, right?

That is, one cannot simply reuse `creduce` scripts with `cvise`?

(not a complaint, just trying to make sure I understand ...)

**Comment by marxin** [comment]
> That's really interesting ... so that means it is _different_ to `creduce`, right?

You are right ;)

From creduce documentation:
_The test script takes no arguments; it should be hard-coded to refer to the same C file that is passed as an argument to C-Reduce._

> 
> That is, one cannot simply reuse `creduce` scripts with `cvise`?

It's bug!

> 
> (not a complaint, just trying to make sure I understand ...)

You are right and I'm going to fix it.

**Comment by andrewvaughanj** [comment]
Phwoar! Look at me go :D

**Comment by marxin** [comment]
> You are right and I'm going to fix it.

Good, I've just pushed fix for this.

**Comment by andrewvaughanj** [comment]
> Good, I've just pushed fix for this.

🙌

**Comment by marxin** [comment]
Should be fixed now.
