### ISSUE TITLE
"--clang-delta-std" ignored?

### ISSUE THREAD

**Issue by andrewvaughanj** [marxin/cvise#46]
This isn't a big deal to me, but I just ran cvise like this:

```bash
cvise --debug --clang-delta-std c++11 --n 97 cvise.sh ac.cpp |& cat > log.txt
```

but I then noticed the following in the log file:

```bash
grep "/usr/libexec/cvise/clang_delta" log.txt | egrep -oh "std=[^ ]*" | sort | uniq -c | sort -n
   1002 std=c++98
   4870 std=c++17
```

So we've done a 1002 instances of c++98 and 4870 of c++17 -- but none of c++11.

Have I missed something, or is this a bug?

This is with:

```
cvise --version
cvise 2.1.0
```

from `2.1.0+git.20210111.972f4ba-1.2` on Tumbleweed.

**Comment by marxin** [comment]
Thanks for the report, confirmed and fixed.

**Comment by andrewvaughanj** [comment]
:boom: I was certain this was going to be user error 😂
