### ISSUE TITLE
cvise leaves temp files around

### ISSUE THREAD

**Issue by doko42** [marxin/cvise#47]
seen with 2.1.0, on https://gcc.gnu.org/PR98107.

$ ls -l tmp*|wc -l
51

using
g++ -c  -fchecking=2 --param=hash-table-verification-limit=1000 foo.ii
in the interestingness test.

**Comment by marxin** [comment]
> seen with 2.1.0, on https://gcc.gnu.org/PR98107.

Are you sure about the PR? This one is a resolved issue.

> 
> $ ls -l tmp*|wc -l
> 51

C-Vise creates `cvise-xxx` folders in the temp directory that should be removed after a pass finishes.
Can you please share paths that are left in temp?

> 
> using
> g++ -c -fchecking=2 --param=hash-table-verification-limit=1000 foo.ii
> in the interestingness test.

Please point me to an attachment you reduce, thanks.

**Comment by doko42** [comment]
sorry, that the one from PR99445.
the tmp files are created in the directory you're starting cvise from.

$ ls -lt tmp* foo.ii*
-rw-rw-r-- 1 doko doko     584 Mar  7 00:41 foo.ii
-rw------- 1 doko doko     646 Mar  7 00:41 tmpmq45e_wt
-rw------- 1 doko doko     641 Mar  7 00:41 tmpetuolquz
-rw------- 1 doko doko     636 Mar  7 00:41 tmpahj7pi11
-rw------- 1 doko doko     631 Mar  7 00:41 tmpxq8bs_wh
-rw------- 1 doko doko     626 Mar  7 00:41 tmptciv79c_
-rw------- 1 doko doko     621 Mar  7 00:41 tmpxrwf9amh
-rw------- 1 doko doko     616 Mar  7 00:41 tmp2str443l
-rw------- 1 doko doko     611 Mar  7 00:41 tmpq5aolbdf
-rw------- 1 doko doko     757 Mar  7 00:41 tmpjmfr5da8
-rw------- 1 doko doko     752 Mar  7 00:41 tmp6ox_32x0
-rw------- 1 doko doko     747 Mar  7 00:41 tmp6gpsndqf
-rw------- 1 doko doko     742 Mar  7 00:41 tmp9hnv61en
-rw------- 1 doko doko     737 Mar  7 00:41 tmpm829dkir
-rw------- 1 doko doko     732 Mar  7 00:41 tmpf2us4zfi
-rw------- 1 doko doko     727 Mar  7 00:41 tmpyny77x04
-rw------- 1 doko doko     722 Mar  7 00:40 tmp4rrxf70o
-rw------- 1 doko doko     803 Mar  7 00:40 tmpgcvonw5i
-rw------- 1 doko doko     798 Mar  7 00:40 tmp1o3cih1a
-rw------- 1 doko doko     793 Mar  7 00:40 tmpqu7mxcuk
-rw------- 1 doko doko     788 Mar  7 00:40 tmpf5s7kcvg
-rw------- 1 doko doko     783 Mar  7 00:40 tmppw3_73ux
-rw------- 1 doko doko     778 Mar  7 00:40 tmpkjdolg4k
-rw------- 1 doko doko     773 Mar  7 00:40 tmpq_mk1zxv
-rw------- 1 doko doko    3209 Mar  7 00:40 tmp_ez_bjte
-rw------- 1 doko doko   53117 Mar  6 23:42 tmpf_la_yo9
-rw------- 1 doko doko  143605 Mar  6 23:29 tmp7ly284ew
-rw------- 1 doko doko  180901 Mar  6 23:24 tmp7mv92x4t
-rw------- 1 doko doko  232048 Mar  6 23:18 tmp8iz92ju4
-rw------- 1 doko doko  301048 Mar  6 23:04 tmpxn_jgg7a
-rw------- 1 doko doko  361250 Mar  6 22:48 tmp2gxhf64p
-rw------- 1 doko doko  435448 Mar  6 22:43 tmpj95033cw
-rw------- 1 doko doko  437901 Mar  6 22:42 tmp4ibpis29
-rw------- 1 doko doko  865953 Mar  6 18:53 tmp8spygoxf
-rw------- 1 doko doko  928786 Mar  6 18:09 tmpaqaacq4j
-rw------- 1 doko doko 1050262 Mar  6 16:20 tmpzime6xtu
-rw------- 1 doko doko 1211305 Mar  6 14:58 tmph1do8tz0
-rw------- 1 doko doko 1457067 Mar  6 13:43 tmpgizvm2i_
-rw------- 1 doko doko 1458032 Mar  6 13:40 tmpvjalaeic
-rw------- 1 doko doko 1457866 Mar  6 13:37 tmpjk8ju1fq
-rw-rw-r-- 1 doko doko 3813718 Mar  5 12:01 foo.ii.orig

**Comment by marxin** [comment]
I can reproduce that.
