### ISSUE TITLE
Redundant sanity passes?

### ISSUE THREAD

**Issue by andrewvaughanj** [marxin/cvise#60]
I'm currently running `cvise` like this:

```bash
cvise --start-with-pass LinesPass::0 --timeout 600 --debug --n $(nproc) cvise.sh unit.cpp
```

and I'm seeing this in the log:

```
00:00:00 DEBUG perform sanity check...
00:00:00 DEBUG sanity check tmpdir = /mnt/baranem/cvise-ja21eq2_
00:00:46 DEBUG sanity check successful
00:00:46 INFO ===< 68660 >===
00:00:46 INFO running 24 interestingness tests in parallel
00:00:46 INFO INITIAL PASSES
00:00:46 DEBUG Creating pass root folder: /mnt/baranem/cvise-m811bv_g
00:00:46 INFO ===< LinesPass::0 >===
00:00:46 DEBUG perform sanity check...
00:00:46 DEBUG sanity check tmpdir = /mnt/baranem/cvise-6403wq4c
00:01:33 DEBUG sanity check successful
```

what I'm surprised at here is that `cvise` runs the sanity check at the start (which is really great!), but also as part of the of the start of `LinesPass`.

Given `cvise` has literally just run the sanity check and made no changes to the input file, I'm surprised it is doing the sanity check again.

This is such a minor nit, but as I noticed it, I thought it was worth sharing. It is "more obvious" to me currently because the interestingness test takes ~45 seconds, so I'm really aware that `cvise` spends 90 seconds "not doing work".

**Comment by marxin** [comment]
The sanity check is needed because `LinessPass` run a formatting utility `topformflat` which modifies the input file and it happened to me that some interestingness tests stop working after the transformation.

**Comment by andrewvaughanj** [comment]
That wasn't what I was saying ... I think here:

```
00:00:46 INFO ===< LinesPass::0 >===
00:00:46 DEBUG perform sanity check...
```

that `cvise` hasn't changed the file yet *at all*.

So, `cvise` starts, it runs the sanity check (great!), it then says "okay, I'm going to do `LinesPass`, but before I do this, I should check the file", and it then runs the sanity check again.

What I'm suggesting is that `cvise` should know if it is going to run *duplicate* sanity checks, and not do them if the file hasn't changed in the middle.

I agree that *after* running `topformflat`, we need to run the test.

**Comment by marxin** [comment]
> that `cvise` hasn't changed the file yet _at all_.

Well, `topformflat` almost always modifies an input file (if it's not something trivial).

> What I'm suggesting is that `cvise` should know if it is going to run _duplicate_ sanity checks, and not do them if the file hasn't changed in the middle.

Sure, we can theoretically have a cache for inputs that are sanitized.

**Comment by andrewvaughanj** [comment]
Actually, maybe I misunderstood. I thought that:

```
00:00:46 DEBUG perform sanity check...
```

meant it happened *before* the first pass of `LinesPass::0` happens.

However, that's not true; `perform sanity check` is printed *after* `topformflat` but *before* removing any lines.

Now I've read the code, I think that this issue can be closed (unless we should rename it for the cache of "already sanitized inputs").

**Comment by marxin** [comment]
Yep, let's close it..
