### ISSUE TITLE
psutil.Process().cpu_affinity() not available on macOS

### ISSUE THREAD

**Issue by arichardson** [marxin/cvise#61]
I just tried running cvise on macOS and it dies with:
`AttributeError: 'Process' object has no attribute 'cpu_affinity'`. Commenting out those lines allows me to continue.
https://psutil.readthedocs.io/en/latest/#psutil.Process.cpu_affinity says `Availability: Linux, Windows, FreeBSD`, so I guess the call could be guarded with a `sys.platform` check?

**Comment by marxin** [comment]
Thank you for the bug report. It should be fixed now. Please let me know if `cvise` works for you on macOS?

**Comment by arichardson** [comment]
Thanks! CVise worked fine for me (other than an LLVM assertion being triggered inside clang-delta, but I think that might be happening because I'm building against a LLVM git snapshot rather than a release).

I also got the following error
```
/Users/alex/cheri/cvise/clang_delta/RewriteUtils.cpp:557:17: error: call to implicitly-deleted copy constructor of 'clang::DeclGroup'
      DeclGroup DGroup = DS->getDeclGroup().getDeclGroup();
                ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/alex/cheri/output/sdk/include/clang/AST/DeclGroup.h:25:25: note: copy constructor of 'DeclGroup' is implicitly deleted because base class 'llvm::TrailingObjects<DeclGroup, Decl *>' has a deleted copy constructor
class DeclGroup final : private llvm::TrailingObjects<DeclGroup, Decl *> {
                        ^
/Users/alex/cheri/output/sdk/include/llvm/Support/TrailingObjects.h:332:3: note: 'TrailingObjects' has been explicitly marked deleted here
  TrailingObjects(const TrailingObjects &) = delete;
  ^
```
which I worked around by changing DGroup to be a reference.

**Comment by marxin** [comment]
Good, I've just pushed the suggested change to master. Let me know if it's fine now?

**Comment by arichardson** [comment]
> Good, I've just pushed the suggested change to master. Let me know if it's fine now?

Yes, I can confirm that it builds out-of-the-box now. Thanks!

**Comment by marxin** [comment]
Great, you're welcome.
