### ISSUE TITLE
Unrecognized arguments --flake8 on Arch

### ISSUE THREAD

**Issue by vlovich** [marxin/cvise#63]
Trying to build this on Arch I get:
```
CMake Warning at CMakeLists.txt:52 (message):
  Pytest package not available: pytest 6.2.4

  ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]

  __main__.py: error: unrecognized arguments: --flake8

    inifile: /home/vlovich/cloudflare/cvise/setup.cfg
    rootdir: /home/vlovich/cloudflare/cvise
```

I tried `pip install flake8` but that didn't seem to help. Removing the `--flake8` from setup.cfg was a workaround but I'm not sure what the right fix is.

**Comment by marxin** [comment]
You'll need to install the `python-pytest-flake8` package:
https://archlinux.org/packages/community/any/python-pytest-flake8/
