### ISSUE TITLE
ClangPass::reduce-class-template-param adds spaces forever

### ISSUE THREAD

**Issue by TestingPlant** [marxin/cvise#73]
When running `cvise /usr/bin/true code.cpp --print-diff --start-with-pass ClangPass::reduce-class-template-param` with the following code:

```cpp
template < Foo(Bar), Qux> struct Structure;
```

cvise just keeps adding spaces.

I'm using cvise 2.4.0-1 from the [AUR package](https://aur.archlinux.org/packages/cvise).

**Comment by marxin** [comment]
Moved to upstream.
