### ISSUE TITLE
Consider moving from `pytest-flake8`

### ISSUE THREAD

**Issue by trofi** [marxin/cvise#77]
Today `nixokgs` [marked `pytest-flake8` as broken](https://github.com/NixOS/nixpkgs/commit/47e7f78fcb4eb96aedeee430a0c4922bdf61d751) for some API problem: https://github.com/tholo/pytest-flake8/issues/87. I'm not sure if it ever gets fixed.

If it does not maybe `cvise` could switch from `pytest-flake8` to something else?

**Comment by marxin** [comment]
Am I correct it's related to Python `3.11`? Have you managed to consume the discussion you linked? If so, is there any chance it gets fixed? If not, is there any fork we can use or so?

**Comment by trofi** [comment]
As I understand the breakage is caused by `flake8-4.x` -> `flake8-5.x` update. `pytest-flake8` fails it's own tests after the update.

Not sure about the maintenance status or alternatives.

**Comment by marxin** [comment]
Oh, I see. Apparently, we've got still `flake8-4.x` in openSUSE Tumbleweed. Lemme ask about package update progress (then I would drop the dependency).

**Comment by bnavigator** [comment]
flake8 v5 is in Tumbleweed now. Because it dropped out of Ring1, it was not held back from a failing pytest-flake8 anymore.

https://build.opensuse.org/request/show/999098
See also https://build.opensuse.org/request/show/998239#comment-1664738
