### ISSUE TITLE
reduction rule endlessly "increses" size

### ISSUE THREAD

**Issue by rguenth** [marxin/cvise#78]
For the testcase below cvise takes

 for (c_scope *scope = current_scope; current_scope;
       scope = scope->outer)

and transforms that to

 for (c_scope *scope = current_scope; current_scope;
       scope = scope->outer->outer)

and so on, endless, eventually running into GCC timeouts with diagnostics even.  The interestingness test is warning vs. no
warning with two custom cc1plus builds.

[t.ii.txt](https://github.com/marxin/cvise/files/9445543/t.ii.txt)

**Comment by rguenth** [comment]
btw, I have cvise 2.4.0 from a Leap 15.3 build in devel:tools, meanwhile the repo is gone though.

**Comment by marxin** [comment]
Can you please provide the interestingness test for that I can run the `t.ii` file?

There was a similar issue for that I have a workaround 80a749e2550c538668b93d4b16372a0a1a47450d which is not in `2.4.0`.

**Comment by marxin** [comment]
> btw, I have cvise 2.4.0 from a Leap 15.3 build in devel:tools, meanwhile the repo is gone though.

Please update to `15.4`, there's a missing `Pebble` package in `15.3` for some reason. I reported that some time ago, but it hasn't been resolved.

**Comment by marxin** [comment]
All right, so based on the provided test-case, 80a749e2550c538668b93d4b16372a0a1a47450d really helps (I decreased the constant to `3`) and I end up with:

```c++
void get_edit_distance_cutoff(int);
struct best_match {
  best_match(int) {}
  void get_best_meaningful_candidate() {
    get_edit_distance_cutoff(m_best_candidate_len);
  }
  int m_best_candidate_len;
};
int current_scope, lookup_name_fuzzy_name;
void lookup_name_fuzzy() {
  best_match bm(lookup_name_fuzzy_name);
  for (; current_scope;)
    bm.get_best_meaningful_candidate();
}
```

where I used `gcc-12` as base and the current master as the second compiler.
